schema_version: 1

context:
  name: gitman
  version: "3.8.1"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gitman-${{ version }}.tar.gz
  sha256: 7f05c37042093c0d8e77bfc0e323007a92c4629f86497a42220e87530fcd3850

build:
  noarch: python
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gitman = gitman.cli:main
      - git-deps = gitman.plugin:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - datafiles >=2.3.1,<3.0.0
    - minilog >=2.3.1,<3.0.0
    - universal-startfile >=0.2,<0.5

tests:
  - python:
      imports:
        - gitman
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - gitman --help
      - git-deps --help

about:
  homepage: https://pypi.org/project/gitman
  license: MIT
  license_file: LICENSE.md
  repository: https://github.com/jacebrowning/gitman
  summary: A language-agnostic dependency manager using Git.

extra:
  recipe-maintainers:
    - jacebrowning
    - diegoferigo
