schema_version: 1

context:
  name: gitman
  version: "3.8"
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gitman-${{ version }}.tar.gz
  sha256: 529c3cc61ff707c7be5b4917e24ee83c9b506a4a9f85886e39c969cdd1c8c8da

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gitman = gitman.cli:main
      - git-deps = gitman.plugin:main

requirements:
  host:
    - python ${{ python_min }}.*,<3.15
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0,<3.15
    - datafiles >=2.3.1,<3.0.0
    - minilog >=2.3.1,<3.0.0
    - universal-startfile >=0.2,<0.4

tests:
  - python:
      imports:
        - gitman
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - gitman --help
      - git-deps --help

about:
  summary: A language-agnostic dependency manager using Git.
  license: MIT
  license_file: LICENSE.md
  homepage: https://pypi.org/project/gitman

extra:
  recipe-maintainers:
    - jacebrowning
    - diegoferigo
